### ISSUE TITLE
Fatal bug

### ISSUE THREAD

**Issue by Occams** [paolo-rossi/delphi-jose-jwt#1]
JOSE.Types.Bytes

This does not seem right

![16-09-_2015_08-46-46](https://cloud.githubusercontent.com/assets/456425/9898127/1f30a018-5c50-11e5-82bf-1929c4a06120.jpg)

This project is in dire need of unit tests.

**Comment by paolo-rossi** [comment]
Hi Occam,

thanks for filing the issue, about unit tests I absolutely agree with you and an extra pair of hands will come in handy.. :-)
