### ISSUE TITLE
Unable to Verify with RSA

### ISSUE THREAD

**Issue by MarkRSill** [paolo-rossi/delphi-jose-jwt#19]
Pulling the latest version I find I am now unable to Verify a JWT with a public key.  I reviewed the change log since it worked previously I see JOSE.Signing.RSA was revised to compile for Linux.  A change made in that revision when reverted corrects Token verification via Public Key.  I don't compile for Linux so don't have a suggestion, but this code needs reviewed to work correctly in Windows.  This change in TRSA.Verify corrects it.
```javascript
  //LByte := IntToStr(ASignature[0]);
  Result := EVP_DigestVerifyFinal( LCtx, PAnsiChar(@ASignature[0]){@LByte}, Length(ASignature) ) = 1;
```

**Comment by MarkRSill** [comment]
Sample application that fails before change and succeeds after change is attached.
[JWTValidateExample.zip](https://github.com/paolo-rossi/delphi-jose-jwt/files/2448070/JWTValidateExample.zip)

**Comment by WynneM** [comment]
Hi guys, anything further on this? I'm having a similar issue but haven't been able to get it working with MarkRSill's example.

**Comment by MarkRSill** [comment]
Validation successful!  Thank you.
