### ISSUE TITLE
Secret base64 encoded 

### ISSUE THREAD

**Issue by oengenheiro** [paolo-rossi/delphi-jose-jwt#2]
Hi Paolo,

How can I verify a token where the secret is base64 encoded?

For example, when I generate a token using your demo and test it at [jwt.io](jwt.io) with key "secret", it returns **"Signature Verified"**. But if I mark the checkbox **"secret base64 encoded"**, it returns **"Invalid Signature"**
The token generated by Auth0 work only with **"secret base64 encoded"** and I'd like to decode it.

**Comment by paolo-rossi** [comment]
Hi Daniel,

finally I had the time to look into your issue... 

to me it appears that the checkbox "secret base64 encoded" on the JWT debugger means only that you have to pass the secret encoded in base64.

So given the key 'secret' you have to pass the value 'c2VjcmV0' ('secret' base64 encoded)

The token itself is not changed and has always been encoded and verified with the key 'secret'.

In the Delphi JOSE library you could find the Base64 coder algorithm in the unit JOSE.Encoding.Base64:
`TBase64.Encode('secret')  =>> 'c2VjcmV0'`

I think that the library itself must not be modified, only the demo, perhaps, could be modified by inserting a checkbox that only decode the secret passed.

I hope I understood your issue.. 

Ciao,
Paolo.
