### ISSUE TITLE
Unable to verify signature with RSA/PEM 

### ISSUE THREAD

**Issue by marceln** [paolo-rossi/delphi-jose-jwt#20]
I'm trying to validate an Amazon Cognito JWT token using the folowing JWK:
```
{
	"alg":"RS256",
	"e": "AQAB",
	"kid": "fgjhlkhjlkhexample=",
	"kty": "RSA",
	"n": "sgjhlk6jp98ugp98up34hpexample",
	"use": "sig"
}

```
Using their examples (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html), I was able to convert the JWT to PEM format and verify the signature on https://jwt.io/.

However, when I try to validate the same token using your library I've got the following error: 'Key is not RSA key in PEM format'

This is the code I've used:
```
function TSampleJWTConsole.VerifySampleToken: string;
var
  LKey: TJWK;
  LToken: TJWT;
  FCompactToken: string;
  FPemKey: string;
begin

  FCompactToken := 'xxxx.yyyy.zzzz';
  FPemKey:=
'-----BEGIN PUBLIC KEY-----' +
'MIIBIjANBg ......bQIDAQAB' +
'-----END PUBLIC KEY-----';


  LKey := TJWK.Create(FPemKey);
  LToken := TJOSE.Verify(LKey, FCompactToken);

  if Assigned(LToken) then
  begin
    try
      if LToken.Verified then
        WriteLn('Token signature is verified')
      else
        WriteLn('Token signature is not verified')
    finally
      LToken.Free;
    end;
  end;
end;

```

Do you have any ideas?

**Comment by paolo-rossi** [comment]
Hi Marcel,

the error you have (generated by OpenSSL) is because your RSA key doesn't appear to be valid.

I've used your sample JWK in [this site](https://npm.runkit.com/jwk-to-pem/src/rsa.js) to generate the RSA PK in PEM format and I've got this PK:
```
"-----BEGIN PUBLIC KEY-----\nMDEwDQYJKoZIhvcNAQEBBQADIAAwHQIWALII4ZZOo6ffLoKffLqd+IaXsWpqZQID\nAQAB\n-----END PUBLIC KEY-----\n"
```
remember that to use the key in Delphi you have to replace the \n with #13#10:
```pascal
PK =
  '-----BEGIN PUBLIC KEY-----'#13#10 +
  'MDEwDQYJKoZIhvcNAQEBBQADIAAwHQIWALII4ZZOo6ffLoKffLqd+IaXsWpqZQID'#13#10 +
  'AQAB'#13#10 +
  '-----END PUBLIC KEY-----'#13#10;
```
I tried using this key with my library and it worked.

Ciao,
Paolo.
