### ISSUE TITLE
Example for using RS256 algorithm with pem file

### ISSUE THREAD

**Issue by jsmith173** [paolo-rossi/delphi-jose-jwt#22]
Hi,

How to sign JWT with an external pem file? (Google Cloud IOT)
I studied TfrmSimple.BuildTokenComplete, probably I have to use it but I don't know how to assign an external pem file, created by openssl.exe.

**Comment by paolo-rossi** [comment]
Hi,

please have a look at the [48fc7c0](https://github.com/paolo-rossi/delphi-jose-jwt/commit/48fc7c0cd2467771226a0eb96a9285656a81b626) commit.. I added the demo for all of the RSA algorithms. If the PEM file contains only the public and private keys, you can open it and pass the structure to the JWT library as shown in the Demo..

Paolo.
