### ISSUE TITLE
Can't use library with Delphi XE

### ISSUE THREAD

**Issue by wadealer** [paolo-rossi/delphi-jose-jwt#25]
How can I use this library with delphi XE? There is no units like `System.SysUtils` or `System.StrUtils`.

**Comment by sersart** [comment]
Hi, can we use this library with Delphi XE6?
Thanks

**Comment by paolo-rossi** [comment]
Hi to all,

sorry for the time it took... this library uses heavily the JSON and NetEncoding stuff so it's better to have a version >= XE7.

This library could be compiled in XE6 but this involve a lot of unit renaming.... speaking of XE, I don't think you'll be able to compile this lib.

Ciao,
Paolo.

**Comment by wadealer** [comment]
Fix README then:
This library has been tested with Delphi 10.2 Tokyo, Delphi 10.1
Berlin and Delphi
XE6 but with a minimum amount of work it should compile with D2010 and
higher

сб, 16 нояб. 2019 г., 18:49 Paolo Rossi <notifications@github.com>:
