### ISSUE TITLE
constructor TJOSEContext.Create shouldn't squash exception and should re-raise

### ISSUE THREAD

**Issue by ByteJuggler** [paolo-rossi/delphi-jose-jwt#27]
The constructor TJOSEContext.Create squashes the exception (EJOSEException.Create('Malformed Compact Serialization')) that is raised when an invalid token string is passed in.  This is almost certainly incorrect as it leaves the caller thinking the construction seemingly succeeded, but being left with what is in reality a partially constructed (invalid) TJOSEContext. 

The consequence is a probable access violation (as is the case in our code ) when for example a custom validator runs, as both GetJOSEObject() and GetJWT() returns nil (due to the failed/partial construction mentioned above).  Additionally there's no way of getting the actual invalid token bytes from the TJOSEContext either which makes raising a further error somewhat problematic.

The fix is to re-raise the exception in the try/except in TJOSEContext.Create.  This results in the correct code being made aware of the failure and given the opportunity to act accordingly.

**Comment by paolo-rossi** [comment]
First of all sorry for the long time it took! 

About the issue: it seems to me that the re-raise of the exception was added in the July 14th 2018 (e90c5c6), please look if that it's the issue you were having problem with.

Ciao,
Paolo.
