### ISSUE TITLE
 Hasura JWT

### ISSUE THREAD

**Issue by timanagement** [paolo-rossi/delphi-jose-jwt#33]
Greetings. How to generate JWT that can contain the data according to this example?

{
	"https://hasura.io/jwt/claims": {
		"x-hasura-user-id": "123456",
		"x-hasura-default-role": "user",
		"x-hasura-allowed-roles": [
			"user"
		]
	},
	"iat": 1579192910,
	"exp": 1579196510,
	"sub": "132456",
	"aud": "https://endpoint.com.br",
	"name": "Empresa"
}

In python I can but in Delphi with Jose I still can not.

I'm grateful right now

**Comment by timanagement** [comment]
In python I can but in Delphi with Jose I still can not.

**Comment by paolo-rossi** [comment]
Hi @timanagement 

you can inherit from TJWTClaims and add all your custom fields. Please have a look at the JWTDemo.Form.Claims unit in the Basic Demo.

Ciao,
Paolo.
