### ISSUE TITLE
Floating Point Error Comparing Times

### ISSUE THREAD

**Issue by ryanwilliams83** [paolo-rossi/delphi-jose-jwt#37]
When validating a JWT;
If the Issued At is the exact same time as the Not Before and the clock skew seconds is set to 0
JoseConsumer will incorrectly error with 'The Expiration Time (exp=%d) claim value cannot be before the NotBefore (nbf=%d) claim value'

This is due to floating point rounding errors

**Comment by paolo-rossi** [comment]
@ryanwilliams83 ,

actually the check is between Int64 values, you can see in action in the TJOSEClaimsValidators.DateClaimsValidator, I've added a new test (TestSameDates) that checks the expiration when IssuedAt and NotBefore are exactly the same and the test passes.

Can you assemble a quick test case that shows the problem?

Thank you,
Paolo.
