### ISSUE TITLE
TSigningBase.LoadPublicKeyFromCert fails for a certifcate loaded from Google Certificate Server

### ISSUE THREAD

**Issue by SchneiderInfosystems** [paolo-rossi/delphi-jose-jwt#43]
I realized that the token verification of the Firebase JWToken within my FB4D library is broken since introducing TRSA.VerifyWithCertificate.

The Google server https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com delivers a certificate based on NID_rsaEncryption.

That is why the FB4D needs the following change:

    class function TSigningBase.LoadPublicKeyFromCert(const ACertificate: TBytes): PEVP_PKEY;
    ...
      LAlg := OBJ_obj2nid(LCer.cert_info.key.algor.algorithm);
      if not((LAlg = JoseSSL.NID_rsaEncryption) or (LAlg = JoseSSL.NID_X9_62_id_ecPublicKey)) then
        raise ESignException.Create('[OpenSSL] Unsupported algorithm type in X509 public key (RSA expected)');`

And in unit JOSE.OpenSSL.Headers:

    // Numeric ASN1 Object Identifiers
    NID_sha256 = 672;
    NID_sha384 = 673;
    NID_sha512 = 674;
    NID_X9_62_id_ecPublicKey = 408; // EC Key
    NID_rsaEncryption = 6;

Perhaps there are other algorithm types that could be supported. Is there a reason for this check and the `ESignException`?

**Comment by paolo-rossi** [comment]
Hi Christoph!

it was a bug, when I moved the method from the ECDSA unit to the "Base" class I forgot to remove the check against the EC Key algorithm. thanks for catching that.. 

Now I added an overload to the LoadPublicKeyFromCert method that accept an Algorithm ID as a parameter and check against it. I also changed the calling routines VerifyWithCertificate in the unit JOSE.Signing.RSA and JOSE.Signing.ECDSA.

Have a good day!
Paolo.

**Comment by SchneiderInfosystems** [comment]
Thank you Paolo for the fast solution!

It works without the restriction of the algorithm type. For me, this solution is perfect because the algorithm of a public certificate can also be subject to change.

Greetings,
Christoph
