### ISSUE TITLE
Brainpool support possible?

### ISSUE THREAD

**Issue by jaenicke** [paolo-rossi/delphi-jose-jwt#46]
Hello,

I had a look at JOSE because I need to verify a JWT, but BP256R1 is not supported yet. Is there any chance, that this could be available soon?

At the moment I am testing with an adapted copy of the ECDSA unit, but as I do not know enough about this topic, I am not sure, whether this is the correct way and whether it will work.

Thank you in advance for any answer!

Sebastian Jänicke

**Comment by paolo-rossi** [comment]
Hello @jaenicke ,

I have to admit that I do not know about brainpool and specifically BP256R1.. if you have links, documentation etc.. please send it to me.

Also if you need I can look at your modified code if you need some help using ECDSA...

Ciao,
Paolo.

**Comment by paolo-rossi** [comment]
Ok @jaenicke if you have something on BP let me know!
