### ISSUE TITLE
Shortcut to TJOSE class functions inside TJWT

### ISSUE THREAD

**Issue by viniciussanchez** [paolo-rossi/delphi-jose-jwt#56]
Today to generate a token, you have to make 2 uses, as the documentation says. And I have to do it like this:

```pascal
function GetToken: string;
var
  LToken: TJWT;
begin
  LToken := TJWT.Create;
  try
    LToken.Claims.NotBefore := Now;
    LToken.Claims.SetClaimOfType('A', 'B');
    Result := TJOSE.SHA256CompactToken('key', LToken);
  finally
    LToken.Free;
  end;
end;
```
What do you think about creating a shortcut inside the TJWT class that calls TJOSE, looking like this:
```pascal
function GetToken: string;
var
  LToken: TJWT;
begin
  LToken := TJWT.Create;
  try
    LToken.Claims.NotBefore := Now;
    LToken.Claims.SetClaimOfType('A', 'B');
    Result := LToken.SHA256CompactToken('key');
  finally
    LToken.Free;
  end;
end;
```
I could do this with all the functions of the TJOSE class. With that I would need to make just one uses to generate the token and it would be simpler and more practical.

**Comment by paolo-rossi** [comment]
Hello @viniciussanchez 

I don't like adding a dependency to TJWT knowing signing algorithms, but now I introduced new interfaces to simplify the token creation:

```delphi
var
  LResult: string;
begin
  LResult := TJOSEProcess.New
    .SetIssuer('Delphi JOSE Library')
    .SetIssuedAt(Now)
    .SetExpiration(Now + 1)
    .SetAlgorithm(LAlg)
    .SetKey(TJOSEAlgorithmId.HS256)
    .Build
    .GetCompactToken
  ;

  memoCompact.Lines.Add(LResult);
end;
```

I hope that this new commit solve the issue.

Paolo.
