### ISSUE TITLE
Azure AD JWT token authorization

### ISSUE THREAD

**Issue by dbcto** [paolo-rossi/delphi-jose-jwt#68]
Hello Paolo.

I have been trying to get the Azure AD JWT token authorization working for the last few days. Unfortunately without success so far. The public key is always rejected by the lib with the error "Key is not RSA key in PEM format". 

I get the appropriate public key via the public access to the keys from Microsoft (property x5c):  
[](https://login.microsoftonline.com/common/discovery/v2.0/keys)

For example:
```
-----BEGIN PUBLIC KEY-----
MIIDBTCCAe2gAwIBAgIQGQ6YG6NleJxJGDRAwAd/ZTANBgkqhkiG9w0BAQsFADAt
MSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4X
DTIyMTAwMjE4MDY0OVoXDTI3MTAwMjE4MDY0OVowLTErMCkGA1UEAxMiYWNjb3Vu
dHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALSS+lq9iVLMS8jXsz0IdSes5+sEqAwIYEWEg5GjLhB8u+VY
pIgfMINuVrkfeoHTKaKJHZUb4e0p0b7Y0DfW+ZuMyQjKUkXCeQ7l5eJnHewoN2ad
QufiZjKvCe5uzkvR6VEGwNcobQh6j+1wOFJ0CNvCfk5xogGt74jy5atOutwquoUM
O42KOcjY3SXFefhUvsTVe1B0eMwDEa7jFB8bXtSGSc2yZsYyqBIycA07XHeg5CN8
q5JmLfBnUJrtGAR0yUmYs/jNdAmNy27y83/rWwTSkP4H5xhihezL0QpjwP2BfwD8
p6yBu6eLzw0V4aRt/wiLd9ezcrxqCMIr9ALfN5ECAwEAAaMhMB8wHQYDVR0OBBYE
FJcSH+6Eaqucndn9DDu7Pym7OA8rMA0GCSqGSIb3DQEBCwUAA4IBAQADKkY0PIys
lgWGmRDKpp/5PqzzM9+TNDhXzk6pw8aESWoLPJo90RgTJVf8uIj3YSic89m4ftZd
mGFXwHcFC91aFe3PiDgCiteDkeH8KrrpZSve1pcM4SNjxwwmIKlJdrbcaJfWRsSo
GFjzbFgOecISiVaJ9ZWpb89/+BeAz1Zpmu8DSyY22dG/K6ZDx5qNFg8pehdOUYY2
4oMamd4J2u2lUgkCKGBZMQgBZFwk+q7H86B/byGuTDEizLjGPTY/sMms1FAX55xB
ydxrADAer/pKrOF1v7Dq9C1Z9QVcm5D9G4DcenyWUdMyK43NXbVQLPxLOng51KO9
icp2j4U7pwHP
-----END PUBLIC KEY-----
```

I have already tested different variants. Structure, header etc. 
If I take the example from the demo application, it works without any problems.

The key is valid via an online check tool.

Here is my Delphi code example:
```
function Validate(AJwt : String; APublicKey : String) : Boolean;
var
  LToken  : TJWT;
  LSigner : TJWS;
  LKey    : TJWK;
begin
  LKey := TJWK.Create;
  try
    LKey.Key := APublicKey;

    LToken  := TJWT.Create;
    LSigner := TJWS.Create(LToken);
    try
      LSigner.SetKey(LKey);
      LSigner.CompactToken := AJwt;

      Result := LSigner.VerifySignature;
    finally
      LToken.Free;
      LSigner.Free;
    end;
  finally
    LKey.Free;
  end;
end;
```

Do you have any idea what I'm doing wrong?
Any hints are welcome. =:)

Best regards
Dennis

**Comment by arimateia** [comment]
Hi @dbcto,

I believe the library only accepts public keys in PKCS1 format. So just convert your PKCS8 key to PKCS1 and try again.

Using OpenSSL, you can do it this way:
```
openssl pkcs8 -topk8 -inform pem -in file.key -outform pem -nocrypt -out file.pem
```

**Comment by dbcto** [comment]
Hey @arimateia ,

Thank you very much for the hint.

I've changed it to:
```
-----BEGIN RSA PUBLIC KEY-----
MIIDBTCCAe2gAwIBAgIQGQ6YG6NleJxJGDRAwAd/ZTANBgkqhkiG9w0BAQsFADAt
MSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4X
DTIyMTAwMjE4MDY0OVoXDTI3MTAwMjE4MDY0OVowLTErMCkGA1UEAxMiYWNjb3Vu
dHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALSS+lq9iVLMS8jXsz0IdSes5+sEqAwIYEWEg5GjLhB8u+VY
pIgfMINuVrkfeoHTKaKJHZUb4e0p0b7Y0DfW+ZuMyQjKUkXCeQ7l5eJnHewoN2ad
QufiZjKvCe5uzkvR6VEGwNcobQh6j+1wOFJ0CNvCfk5xogGt74jy5atOutwquoUM
O42KOcjY3SXFefhUvsTVe1B0eMwDEa7jFB8bXtSGSc2yZsYyqBIycA07XHeg5CN8
q5JmLfBnUJrtGAR0yUmYs/jNdAmNy27y83/rWwTSkP4H5xhihezL0QpjwP2BfwD8
p6yBu6eLzw0V4aRt/wiLd9ezcrxqCMIr9ALfN5ECAwEAAaMhMB8wHQYDVR0OBBYE
FJcSH+6Eaqucndn9DDu7Pym7OA8rMA0GCSqGSIb3DQEBCwUAA4IBAQADKkY0PIys
lgWGmRDKpp/5PqzzM9+TNDhXzk6pw8aESWoLPJo90RgTJVf8uIj3YSic89m4ftZd
mGFXwHcFC91aFe3PiDgCiteDkeH8KrrpZSve1pcM4SNjxwwmIKlJdrbcaJfWRsSo
GFjzbFgOecISiVaJ9ZWpb89/+BeAz1Zpmu8DSyY22dG/K6ZDx5qNFg8pehdOUYY2
4oMamd4J2u2lUgkCKGBZMQgBZFwk+q7H86B/byGuTDEizLjGPTY/sMms1FAX55xB
ydxrADAer/pKrOF1v7Dq9C1Z9QVcm5D9G4DcenyWUdMyK43NXbVQLPxLOng51KO9
icp2j4U7pwHP
-----END RSA PUBLIC KEY-----
```

The result is unfortunately:
```
Could not read key from d:\pub.key
C41C0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto\store\store_result.c:151:
```

Without changing to -----BEGIN RSA PUBLIC KEY----- it's only "Could not read key from d:\pub.key".

**Comment by dbcto** [comment]
...but you pointed me in the right direction! =:)

The key is in X.509 format - so I converted this to a pem:
`openssl x509 -pubkey -noout -in d:\public.crt > d:\pubkey.pem`

public.crt:
```
-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIQGQ6YG6NleJxJGDRAwAd/ZTANBgkqhkiG9w0BAQsFADAt
MSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4X
DTIyMTAwMjE4MDY0OVoXDTI3MTAwMjE4MDY0OVowLTErMCkGA1UEAxMiYWNjb3Vu
dHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALSS+lq9iVLMS8jXsz0IdSes5+sEqAwIYEWEg5GjLhB8u+VY
pIgfMINuVrkfeoHTKaKJHZUb4e0p0b7Y0DfW+ZuMyQjKUkXCeQ7l5eJnHewoN2ad
QufiZjKvCe5uzkvR6VEGwNcobQh6j+1wOFJ0CNvCfk5xogGt74jy5atOutwquoUM
O42KOcjY3SXFefhUvsTVe1B0eMwDEa7jFB8bXtSGSc2yZsYyqBIycA07XHeg5CN8
q5JmLfBnUJrtGAR0yUmYs/jNdAmNy27y83/rWwTSkP4H5xhihezL0QpjwP2BfwD8
p6yBu6eLzw0V4aRt/wiLd9ezcrxqCMIr9ALfN5ECAwEAAaMhMB8wHQYDVR0OBBYE
FJcSH+6Eaqucndn9DDu7Pym7OA8rMA0GCSqGSIb3DQEBCwUAA4IBAQADKkY0PIys
lgWGmRDKpp/5PqzzM9+TNDhXzk6pw8aESWoLPJo90RgTJVf8uIj3YSic89m4ftZd
mGFXwHcFC91aFe3PiDgCiteDkeH8KrrpZSve1pcM4SNjxwwmIKlJdrbcaJfWRsSo
GFjzbFgOecISiVaJ9ZWpb89/+BeAz1Zpmu8DSyY22dG/K6ZDx5qNFg8pehdOUYY2
4oMamd4J2u2lUgkCKGBZMQgBZFwk+q7H86B/byGuTDEizLjGPTY/sMms1FAX55xB
ydxrADAer/pKrOF1v7Dq9C1Z9QVcm5D9G4DcenyWUdMyK43NXbVQLPxLOng51KO9
icp2j4U7pwHP
-----END CERTIFICATE-----
```

With the generated pubkey.pem I was able to validate the JWT!

@paolo-rossi is this supported in the future or any other possibility to handle that?

**Comment by dbcto** [comment]
I digged a bit deeper into that and found a solution to convert the X.509 certificate with Indy `IdSSLOpenSSLHeaders` (plus a small extra declaration of `X509_get_pubkey` - because this is not finally defined in the Indy headers) to a public key that can be used here.

If you are interested I can make a small pull request.

Best 
Dennis

**Comment by paolo-rossi** [comment]
Hello @dbcto 

thank you for taking the time to open this issue and thank you @arimateia for... resolving it! :-)

Now, regarding the issue:

I don't think it's wrong to have an homogeneous repository of private keys/certificates originating from different services/systems (Azure/Apple/AWS/Google/etc...) because every service tend to export keys/certificates in different formats, so I find useful to have such repository where I can perform automated "key management" on these objects using the same commands.

That said it would be certainly nice to have converting function callable directly from the code, so Dennis yes, I'm interested in a PR regarding the argument.

The difficulty here are the numbers of API not imported by Indy, but it's not an impossible task. Quite frankly I hit the pause button on the OpenSSL API because I was hoping to see the merge of OpenSSL 1.1 (or 3.0) in the Indy main repo but.... no luck yet :-(

If we want to discuss further this topic we can move on the Discussions tab here on GitHub.

Thank you both!

Ciao,
Paolo.

**Comment by dbcto** [comment]
Hey Paolo,

I've created a small PR to support the X.509 certificates in TJWS.VerifySignature.
I have seen that you have already made the necessary imports of OpenSSL and even implemented the appropriate functions. So it was only a very small extension after all.

> The difficulty here are the numbers of API not imported by Indy, but it's not an impossible task. Quite frankly I hit the pause button on the OpenSSL API because I was hoping to see the merge of OpenSSL 1.1 (or 3.0) in the Indy main repo but.... no luck yet :-(

This is what we all hope for =:)

Ciao,
Dennis
