### ISSUE TITLE
unreliable Check für Booleans in JSON

### ISSUE THREAD

**Issue by BaumiCoder** [paolo-rossi/delphi-jose-jwt#72]
### Problem
I lately noticed a very unhappy behavior in the JSON Boolean classes of Delphi. If you check for an true JSON boolean value like this:
```pascal
Result := aValue is TJSONTrue;
``` 
You maybe get `False` as result, although it is a `TJSONValue` with a Boolean true inside. If you created it like this:
```pascal
aValue := TJSONBool.Create(True);
// or with a default function, that creates a TJSONBool internal
var aObj: TJSONObject := TJSONObject.Create;
try
  // ...
  aObj.AddPair('myBoolean',True);
  // ...
finally
  FreeAndNil(aObj);
end;
```
the result is `False`. The reason for this is the hierarchy of inheritance. The classes [TJSONTrue](https://docwiki.embarcadero.com/Libraries/Alexandria/en/System.JSON.TJSONTrue) and [TJSONFalse](https://docwiki.embarcadero.com/Libraries/Alexandria/en/System.JSON.TJSONFalse) are derived from [TJSONBool](https://docwiki.embarcadero.com/Libraries/Alexandria/en/System.JSON.TJSONBool).

### Solution
To have a reliable check for boolean in JSON you should use `TJSONBool`. For example like this:
```pascal
if aValue is TJSONBool then
  Result := TJSONBool(aValue).AsBoolean
else
  Result := False; // or something other suitable value / action
```

## Place in JWT
In JWT there is such unreliable check in the code in [JOSE.Types.JSON.pas line 90-93](https://github.com/paolo-rossi/delphi-jose-jwt/blob/8e133c047ce2606f7418afe9d7e68b0ddf1f9e30/Source/Common/JOSE.Types.JSON.pas#L90).
I only randomly noticed it in JWT at search through a codebase including JWT. I didn't encountered a specific bug in JWT, that is triggered by this.

**Comment by paolo-rossi** [comment]
Hello @BaumiCoder 

thanks for taking the time with this issue... I was not aware of this problem with Delphi, do you have a report number in Embarcadero's Quality Portal ?

I will fix the issue and in the meantime I've reworked the conditional directives in the JOSE project... thank you again..

Ciao,
Paolo.

**Comment by BaumiCoder** [comment]
I don't know, if there is a report on the Quality Portal of Embarcadero. I am not sure, if it is only an unusual behavior or a real bug. The only solution for Embarcadero would be to mark the classes `TJSONTrue` and `TJSONFalse` as deprecated.
The only save usage of the classes is `TJSONTrue.Create` / `TJSONFalse.Create`, but that  be substituted with `TJSONBool.Create(True)` / `TJSONBool.Create(False)`.

I will think about it.

**Comment by BaumiCoder** [comment]
FYI: I created a ticket at Embarcadero:
https://quality.embarcadero.com/browse/RSP-42322
(Sadly the tickets there are only available with EDN Account login.)
