### ISSUE TITLE
json.pas file is missing

### ISSUE THREAD

**Issue by KamleshJaiswar** [paolo-rossi/delphi-jose-jwt#74]
While compiling the issue is system.json.pas file is missing how to get the correct system.json.pas file

**Comment by paolo-rossi** [comment]
Hello @KamleshJaiswar 

there is no file system.json.pas in he Delphi JWT library, is perhaps another piece of code that reference that file... can you check in that?

Paolo.

**Comment by KamleshJaiswar** [comment]
Hi @paolo-rossi this JWT source code supports Delphi xe5 as well.

**Comment by paolo-rossi** [comment]
Sorry I hadn't realized it was the standard System.JSON unit.... and no, unfortunately Delphi JOSE supports Delphi XE6 and later....

Paolo.
