### ISSUE TITLE
Read the payload of a token

### ISSUE THREAD

**Issue by aosh50** [paolo-rossi/delphi-jose-jwt#8]
My token is verified, how do I then get the value of the payload of the token??

var
  lKey: TJWK;
  lToken: TJWT;
begin
  lKey := TJWK.Create('secret');
  // Unpack and verify the token
  lToken := TJOSE.Verify(lKey, AToken);

  if Assigned(lToken) then
  begin
    try
      if lToken.Verified then
      begin
        /*******In here I would like to get the string value of the payload******/
        //Result := TJSONUtils.ToJSON(lToken.Claims.JSON);
        end;
    finally
      lToken.Free;
    end;
  end;

**Comment by paolo-rossi** [comment]
Using the TJOSE class is the most simple way to do to verify the token but if you want to access to the raw payload (or header or signature) you have to use directly the TJWS class (if you open the TJOSE.Verify() method you can see how). For simplicity I report the code here:

``` delphi
var
  LToken: TJWT;
  LSigner: TJWS;
  LPayload: TBytes;
begin  
  LToken := TJWT.Create;
  try
    LSigner := TJWS.Create(LToken);
    try
      LSigner.SkipKeyValidation := True;
      LSigner.SetKey(AKey);
      LSigner.CompactToken := ACompactToken;
      
      if LSigner.VerifySignature then
      begin
        // The Token is verified, you can access to its claims
        LWJT.Claims.....
        
        // Here you can also access to the raw JWS payload/header/signature 
        LPayload := LSigner.Payload;
      
      end;
    finally
      LSigner.Free;
    end;
  finally
    FreeAndNil(LToken);
  end;

```
