### ISSUE TITLE
Add Custom Validators to TJOSEConsumer/TJOSEConsumerBuilder

### ISSUE THREAD

**Issue by jrunyan77** [paolo-rossi/delphi-jose-jwt#82]
Currently TJOSEConsumer and TJOSEConsumerBuilder does not support adding additional claims.

One approach would be to derive new classes with the additional claims and validators. However, the members needed are marked as private.

The other approach would be to allow access to SetValidators in the TJOSEConsumer class. The builder would build the base consumer and then the additional validators could be added before the ProcessContext procedure is called.

**Comment by paolo-rossi** [comment]
Answered in discussions
