### ISSUE TITLE
Error on choosing ES256 signing algorithm

### ISSUE THREAD

**Issue by duzzell** [paolo-rossi/delphi-jose-jwt#85]
Thank you for providing this work. It's very useful to me.

I'm using JOSE & JWT to generate the secret for Sign In with Apple from the private key file supplied by Apple. Apple requires the ES256 signing algorithm. Running Delphi 12.1 on Windows 10 and compiling for Win64, choosing TJOSEAlgorithmId.ES256 for the signing algorithm caused a protection fault when I called LSigner.Sign(LKey, LAlg). I found the fault was not generated when I changed a couple of lines in class function TECDSA.Sig2OctetSequence from this:

```
    JoseSSL.BN_bn2bin(ASignature.r, Pointer(Integer(Result) + (LSigLength div 2) - LRLength));
    JoseSSL.BN_bn2bin(ASignature.s, Pointer(Integer(Result) + LSigLength - LSLength));

```		
to this:

```
{$IFDEF CPU64BITS}
    JoseSSL.BN_bn2bin(ASignature.r, Pointer(int64(Result) + (LSigLength div 2) - LRLength));
    JoseSSL.BN_bn2bin(ASignature.s, Pointer(int64(Result) + LSigLength - LSLength));
{$ELSE}
    JoseSSL.BN_bn2bin(ASignature.r, Pointer(Integer(Result) + (LSigLength div 2) - LRLength));
    JoseSSL.BN_bn2bin(ASignature.s, Pointer(Integer(Result) + LSigLength - LSLength));
{$ENDIF CPU64BITS}

```
I belive I'm a happy camper now.

Thanks again.

David

**Comment by sglienke** [comment]
The proper fix would be this:

```
  JoseSSL.BN_bn2bin(ASignature.r, Pointer(NativeInt(Result) + (LSigLength div 2) - LRLength));
  JoseSSL.BN_bn2bin(ASignature.s, Pointer(NativeInt(Result) + LSigLength-LSLength));
```

FWIW more places in the codebase do wrong casts of Pointer to Integer and need fixing.

**Comment by duzzell** [comment]
I agree, but my impression is that NativeInt can no longer be used for casting in Delphi. It may be that there are situations where it can be used and situations where it can't. I haven't studied it that hard - I just want a solution that works.

Get BlueMail <https://bluemail.me> for Desktop

Stefan Glienke wrote:



The proper fix would be this:


  JoseSSL.BN_bn2bin(ASignature.r, Pointer(NativeInt(Result) + (LSigLength div 2) - LRLength));
  JoseSSL.BN_bn2bin(ASignature.s, Pointer(NativeInt(Result) + LSigLength-LSLength));


FWIW more places in the codebase do wrong casts of Pointer to Integer and need fixing.

**Comment by duzzell** [comment]
Hmmmm. I just ran across a bunch of errors that look like this:

```
function SQLQuotedStr(Src: PWideChar; Len: LengthInt; Quote: WideChar)
  : UnicodeString; overload;
var
    P, Dest, PEnd, PFirst: PWideChar;
begin
    Dest := Nil;
    P := Src;
    PEnd := P + Len;
    PFirst := nil;
    while P < PEnd do
    begin
        if (P^ = Quote) then
        begin
            if Dest = nil then
                PFirst := P;
            Inc(NativeUInt(Dest));  <== error here
        end;
        Inc(P);
    end;

```		
In this bit of doc (http://docwiki.embarcadero.com/Libraries/Athens/en/System.NativeInt) I read this snippit:
		
		_As of RAD Studio 12.0, in the Delphi compiler, NativeInt becomes a weak alias, meaning that it cannot be used as a separate type anymore. It can be used instead of the two counterparts, but you cannot overload methods using both NativeInt and one of the matching native types, since this will give an error.
Note: To avoid ambiguity, conversions must be explicit, as the following code example illustrates.

  NativeInt ni = 100; //Wrong. Will issue an Error
  NativeInt ni = NativeInt(100); //Correct
  System::GetMemory(0x100); // Error
  System::GetMemory(NativeInt(0x100)); //Correct_

I didn't fully understand that, but it lead me to fix the errors by doing this:

```
function SQLQuotedStr(Src: PWideChar; Len: LengthInt; Quote: WideChar)
  : UnicodeString; overload;
var
    P, Dest, PEnd, PFirst: PWideChar;
begin
    Dest := Nil;
    P := Src;
    PEnd := P + Len;
    PFirst := nil;
    while P < PEnd do
    begin
        if (P^ = Quote) then
        begin
            if Dest = nil then
                PFirst := P;
{$IFDEF CPU32BITS}
            Inc(UInt32(Dest));
{$ENDIF CPU32BITS}
{$IFDEF CPU64BITS}
            Inc(UInt64(Dest));
{$ENDIF CPU64BITS}
//            Inc(NativeUInt(Dest));
        end;
        Inc(P);
    end;

```
This solution works for me. How would you have fixed the error?

**Comment by sglienke** [comment]
This statement in the docs refers to method overloading where before you could have this:

```
procedure Foo(i: Integer); overload;
procedure Foo(i: Int64); overload;
procedure Foo(i: NativeInt); overload;
```
which worked because NativeInt was a distinct type - since Delphi 12 this code will not compile anymore because now depending on the target architecture it collides with Integer or Int64 because as said its an alias for them.
